--CREATE DATABASE EXEC_PC_II;
--USE EXEC_PC_II;
CREATE TABLE CLIENTE(
COD_CLIENTE             INTEGER AUTO_INCREMENT NOT NULL,
NOME                    VARCHAR(100),
SOBRENOME               VARCHAR(100),
CPF                     VARCHAR(20),
ENDERECO                VARCHAR(100),
CIDADE                  VARCHAR(50),
ESTADO                  VARCHAR(2),
FLG_ATIVO			   CHAR(1),

PRIMARY KEY (COD_CLIENTE)
);


CREATE TABLE FORNECEDOR(
COD_FORNECEDOR          INTEGER AUTO_INCREMENT NOT NULL,
NOME_FORNECEDOR         VARCHAR(100),
CIDADE                  VARCHAR(50),
ESTADO                  VARCHAR(2),
FLG_ATIVO			   CHAR(1),

PRIMARY KEY (COD_FORNECEDOR)
);

CREATE TABLE PRODUTO (

COD_PRODUTO        INTEGER AUTO_INCREMENT NOT NULL,
COD_FORNECEDOR     INTEGER,
NOME_PRODUTO       VARCHAR(50),
PRECO_UNITARIO     DECIMAL(5,2),
FLG_ATIVO			   CHAR(1),

PRIMARY KEY(COD_PRODUTO),
FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

CREATE TABLE VENDA(

COD_VENDA   INTEGER AUTO_INCREMENT NOT NULL,
COD_CLIENTE       INTEGER,
VALOR_TOTAL       DECIMAL(5,2),
DATA_NOTA         DATE,

PRIMARY KEY (COD_VENDA),
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)

);


CREATE TABLE ITEM_VENDA(

COD_ITEM         INTEGER AUTO_INCREMENT NOT NULL,
COD_VENDA        INTEGER,
COD_PRODUTO      INTEGER,
QUANTIDADE       INTEGER,

PRIMARY KEY (COD_ITEM),
FOREIGN KEY (COD_VENDA) REFERENCES VENDA(COD_VENDA),
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);


--MASSA DE DADOS FORNECEDOR
INSERT INTO FORNECEDOR(NOME_FORNECEDOR, CIDADE, ESTADO) VALUES ('REFRESCOS ITUBAINA', 'RIBEIRAO PRETO', 'SP');
INSERT INTO FORNECEDOR(NOME_FORNECEDOR, CIDADE, ESTADO) VALUES ('CAFES ABC', 'GUAXUPE', 'MG');
INSERT INTO FORNECEDOR(NOME_FORNECEDOR, CIDADE, ESTADO) VALUES ('CALCADOS PE-DE-BOI', 'FRANCA', 'SP');
INSERT INTO FORNECEDOR(NOME_FORNECEDOR, CIDADE, ESTADO) VALUES ('ELETRONICOS SAO PAULO', 'SAO PAULO', 'SP');
INSERT INTO FORNECEDOR(NOME_FORNECEDOR, CIDADE, ESTADO) VALUES ('SUCO LARANJEX', 'SAO PAULO', 'SP');
INSERT INTO FORNECEDOR(NOME_FORNECEDOR, CIDADE, ESTADO) VALUES ('QUEIJO TOP', 'BELO HORIZONTE', 'MG');
INSERT INTO FORNECEDOR(NOME_FORNECEDOR, CIDADE, ESTADO) VALUES ('PAMONHAS AMARELINHAS', 'PIRACICABA', 'SP');

SELECT * FROM FORNECEDOR;

--MASSA DE DADOS PRODUTOS
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('1', 'GUARANA', '1.50');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('1', 'REFRESCO DE COLA', '2.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('1', 'SUCO DE LARANJA', '1.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('1', 'CACHACA OLHO VERMELHO', '3.00');
--
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('2', 'CAFE ESPRESSO', '17.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('2', 'CAFE EXTRA FORTE', '16.25');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('2', 'CAFE TRADICIONAL', '12.50');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('2', 'CAFE EM GRAOS', '30.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('2', 'CAPUCCINO', '6.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('2', 'CAFE ARABICA SACA', '587.00');
--
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('3', 'SAPATO MASCULINO', '40.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('3', 'CHINELAO', '10.00');
--
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('4', 'SMARTPHONE', '799.00');
--
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('5', 'QUEIJO FINO', '17.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('5', 'QUEIJO MINEIRO', '15.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('5', 'QUEIJO CANASTRA', '23.00');
--
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('6', 'PAMONHA SALGADA', '3.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('6', 'PAMONHA DOCE', '3.00');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('6', 'PAMONHA SALGADA COM QUEIJO', '3.50');
INSERT INTO PRODUTO(COD_FORNECEDOR, NOME_PRODUTO, PRECO_UNITARIO) VALUES ('6', 'PAMONHA DOCE COM QUEIJO', '3.50');
--
SELECT * FROM PRODUTO;
--
--MASSA DE DADOS NOTA FISCAL
INSERT INTO VENDA (DATA_NOTA) VALUES ((SYSDATE()-1));
INSERT INTO VENDA (DATA_NOTA) VALUES ((SYSDATE()-17));
INSERT INTO VENDA (DATA_NOTA) VALUES ((SYSDATE()));
--
--MASSA DE DADOS ITENS NOTA FISCAL
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (1,1,10);
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (1,2,50);
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (1,3,5);
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (1,4,10);
--
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (2,7,10);
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (2,9,1);
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (2,19,5);
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (2,17,3);
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (2,15,1);
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (2,11,1);
--
INSERT INTO ITEM_VENDA(COD_VENDA, COD_PRODUTO, QUANTIDADE) VALUES (3,13,1);