--CREATE DATABASE EXEC_PC_II;
--USE EXEC_PC_II;
CREATE TABLE CLIENTE(
COD_CLIENTE             INTEGER AUTO_INCREMENT NOT NULL,
NOME                    VARCHAR(100),
SOBRENOME               VARCHAR(100),
CPF                     VARCHAR(20),
ENDERECO                VARCHAR(100),
CIDADE                  VARCHAR(50),
ESTADO                  VARCHAR(2),
FLG_ATIVO			   CHAR(1),

PRIMARY KEY (COD_CLIENTE)
);


CREATE TABLE FORNECEDOR(
COD_FORNECEDOR          INTEGER AUTO_INCREMENT NOT NULL,
NOME_FORNECEDOR         VARCHAR(100),
CIDADE                  VARCHAR(50),
ESTADO                  VARCHAR(2),
FLG_ATIVO			   CHAR(1),

PRIMARY KEY (COD_FORNECEDOR)
);

CREATE TABLE PRODUTO (

COD_PRODUTO        INTEGER AUTO_INCREMENT NOT NULL,
COD_FORNECEDOR     INTEGER,
NOME_PRODUTO       VARCHAR(50),
PRECO_UNITARIO     DECIMAL(5,2),
FLG_ATIVO			   CHAR(1),

PRIMARY KEY(COD_PRODUTO),
FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

CREATE TABLE VENDA(

COD_VENDA   INTEGER AUTO_INCREMENT NOT NULL,
COD_CLIENTE       INTEGER,
VALOR_TOTAL       DECIMAL(5,2),
DATA_NOTA         DATE,

PRIMARY KEY (COD_VENDA),
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)

);


CREATE TABLE ITEM_VENDA(

COD_ITEM         INTEGER AUTO_INCREMENT NOT NULL,
COD_VENDA        INTEGER,
COD_PRODUTO      INTEGER,
QUANTIDADE       INTEGER,

PRIMARY KEY (COD_ITEM),
FOREIGN KEY (COD_VENDA) REFERENCES VENDA(COD_VENDA),
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);
